export enum MODULOS {
    HOME,
    ARTICULOS_LISTAR,
    ARTICULOS_CREAR,
    ARTICULOS_EDITAR,
    MATCH_AUTOR,
    MATCH_EDITOR,
    MODAL, 
    VER_PERFIL,
    EDITAR_PERFIL,
    MIS_MATCH,
    CONTACTO_MATCH
}